"""improve a  reviews

Revision ID: 036722120ea3
Revises: 7170468e79fb
Create Date: 2024-02-28 11:23:00.817899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036722120ea3'
down_revision = '7170468e79fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
